import os
import shutil
import plotly.io as pio
from typing import Optional


class TempFileService:
    """
    Service class for managing temporary files generated by the application.

    This service is primarily used for storing Plotly figures rendered as
    standalone HTML files and for cleaning up temporary files on application exit.
    """

    def __init__(
            self,
            temp_dir: str = "data/temp"
    ) -> None:
        """
        Initialize the temporary file service.

        Ensures that the temporary directory exists.

        Args:
            temp_dir (str, optional):
                Path to the directory used for temporary files.
                Defaults to "data/temp".
        """

        self.temp_dir = temp_dir
        os.makedirs(self.temp_dir, exist_ok=True)

    def save_plot_html(
            self,
            fig,
            name: str
    ) -> Optional[str]:
        """
        Save a Plotly figure as an HTML file in the temporary directory.

        The generated file contains a fully standalone HTML document
        with embedded Plotly JavaScript.

        Args:
            fig (plotly.graph_objs.Figure):
                Plotly figure to be saved.
            name (str):
                Name of the output HTML file (e.g. "plot_1.html").

        Returns:
            Optional[str]:
                Absolute path to the saved HTML file if successful,
                or None if the figure is None.
        """
        if fig is None:
            return None
        path = os.path.join(self.temp_dir, name)
        html = pio.to_html(fig, include_plotlyjs=True, full_html=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)
        return os.path.abspath(path)

    def cleanup(self):
        """
        Remove all files and subdirectories inside the temporary directory.

        The temporary directory itself is preserved.
        """
        if os.path.isdir(self.temp_dir):
            for filename in os.listdir(self.temp_dir):
                file_path = os.path.join(self.temp_dir, filename)
                try:
                    if os.path.isfile(file_path) or os.path.islink(file_path):
                        os.remove(file_path)
                    elif os.path.isdir(file_path):
                        shutil.rmtree(file_path)
                except Exception as e:
                    print(f"Error deletion {file_path}: {e}")
